name: Windows-Test

on:
  push:

env: 
  ROS_DISTRO: foxy

jobs:
  windows-amd64-build-and-test: # No rostooling/setup-ros-docker docker images available for Windows.
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup ROS
        uses: ros-tooling/setup-ros@c4e8165ee5518c04dc4588bff7c1028ccf563e6f # Includes latest Foxy Windows release (Patch 5)
        with:
          required-ros-distributions: ${{ env.ROS_DISTRO }}

      - name: Build ROS2 Packages and Run Tests
        uses: wmmc88/action-ros-ci@wmmc88/fix-windows-builds
        with:
          target-ros2-distro: ${{ env.ROS_DISTRO }}