name: Windows-Test

on:
  push:

env: 
  ROS_DISTRO: foxy

jobs:
  windows-amd64-build-and-test: # No rostooling/setup-ros-docker docker images available for Windows.
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup ROS
        # uses: ros-tooling/setup-ros@c4e8165ee5518c04dc4588bff7c1028ccf563e6f # Includes latest Foxy Windows release (Patch 5)
        uses: wmmc88/setup-ros@wmmc88/install-correct-python-version-windows # includes openssl fix too
        with:
          required-ros-distributions: ${{ env.ROS_DISTRO }}
      - name: TEST
        run: |
          $env:PATH -split ';'
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          sudo: false
      - name: Build ROS2 Packages and Run Tests
        uses: wmmc88/action-ros-ci@fix-windows-builds-2
        with:
          target-ros2-distro: ${{ env.ROS_DISTRO }}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          sudo: false